/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shelfstockers;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.impl.sql.compile.TableName;

/**
 *
 * @author siddharthachoudhary
 */
public class BillingForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form BillingForm
     */
    public BillingForm() {
        initComponents();
        
    }
    int TotAmt=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        sstockersPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("sstockersPU").createEntityManager();
        stockQuery = java.beans.Beans.isDesignTime() ? null : sstockersPUEntityManager.createQuery("SELECT s FROM Stock s");
        stockList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : stockQuery.getResultList();
        stockQuery1 = java.beans.Beans.isDesignTime() ? null : sstockersPUEntityManager.createQuery("SELECT s FROM Stock s");
        stockList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : stockQuery1.getResultList();
        stockQuery2 = java.beans.Beans.isDesignTime() ? null : sstockersPUEntityManager.createQuery("SELECT s FROM Stock s");
        stockList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : stockQuery2.getResultList();
        stockQuery3 = java.beans.Beans.isDesignTime() ? null : sstockersPUEntityManager.createQuery("SELECT s FROM Stock s");
        stockList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : stockQuery3.getResultList();
        stockQuery4 = java.beans.Beans.isDesignTime() ? null : sstockersPUEntityManager.createQuery("SELECT s FROM Stock s");
        stockList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : stockQuery4.getResultList();
        stockQuery5 = java.beans.Beans.isDesignTime() ? null : sstockersPUEntityManager.createQuery("SELECT s FROM Stock s");
        stockList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : stockQuery5.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextQty = new javax.swing.JTextField();
        TextPrice = new javax.swing.JTextField();
        TextId = new javax.swing.JTextField();
        TextAmount = new javax.swing.JTextField();
        SelectBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableName = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        MainTable = new javax.swing.JTable();
        TextTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextMessage = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel3.setText("Quantity");

        jLabel4.setText("Unit Price");

        jLabel5.setText("Amount");

        TextQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextQtyFocusLost(evt);
            }
        });
        TextQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextQtyActionPerformed(evt);
            }
        });

        TextPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPriceActionPerformed(evt);
            }
        });

        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });

        TextAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAmountActionPerformed(evt);
            }
        });

        SelectBtn.setText("Select");
        SelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectBtnActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, stockList4, TableName);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, stockList, org.jdesktop.beansbinding.ELProperty.create("$name"), TableName, org.jdesktop.beansbinding.BeanProperty.create("selectedElements"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(TableName);

        MainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "QUANTITY", "PRICE", "AMOUNT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MainTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(MainTable);
        MainTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel6.setText("Total Amount:");

        jLabel7.setText("Status:");

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TextMessage.setEditable(false);
        TextMessage.setBackground(new java.awt.Color(204, 204, 204));
        TextMessage.setColumns(20);
        TextMessage.setRows(1);
        TextMessage.setTabSize(10);
        TextMessage.setAutoscrolls(false);
        jScrollPane3.setViewportView(TextMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextQty, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(TextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(TextAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SelectBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SelectBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextQtyActionPerformed

    private void TextPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPriceActionPerformed

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    private void TextAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAmountActionPerformed

    private void SelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectBtnActionPerformed

// TODO add your handling code here:

    int row=TableName.getSelectedRow();
    int column=TableName.getSelectedColumn();
    String name1=(String)TableName.getValueAt(row, column);
    DefaultTableModel model = (DefaultTableModel)MainTable.getModel();
   UpdateBill ub=new UpdateBill();
   int id=ub.m1(name1);
   int price=ub.m2(name1);
   
  
  if(TextQty.getText().isEmpty())
  {
      TextMessage.setText("Enter some quantity");
  }
  else
  {
      int qty=Integer.parseInt(TextQty.getText());
  int amount=price*qty;
  TotAmt+=amount; 
    TextTotal.setText(""+TotAmt);
    
    
      model.addRow(new Object[]{id,name1,qty,price,amount});
    TextId.setText("");
    TextQty.setText("");
    TextAmount.setText("");
    TextPrice.setText("");
    TextMessage.setText("Item is added");
  }
    
    
    
    
    
    
    
    
    
    }//GEN-LAST:event_SelectBtnActionPerformed

    private void TextQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextQtyFocusLost
        // TODO add your handling code here:
        int row=TableName.getSelectedRow();
    int column=TableName.getSelectedColumn();
    String name1=(String)TableName.getValueAt(row, column);
    DefaultTableModel model = (DefaultTableModel)MainTable.getModel();
   UpdateBill ub=new UpdateBill();
   int id=ub.m1(name1);
   int price=ub.m2(name1);
   int qty=Integer.parseInt(TextQty.getText());
   int amt=qty*price;
   TextAmount.setText(""+amt);
   TextPrice.setText(""+price);
   TextId.setText(""+id);
    }//GEN-LAST:event_TextQtyFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MainTable;
    private javax.swing.JButton SelectBtn;
    private javax.swing.JTable TableName;
    private javax.swing.JTextField TextAmount;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextArea TextMessage;
    private javax.swing.JTextField TextPrice;
    private javax.swing.JTextField TextQty;
    private javax.swing.JTextField TextTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.persistence.EntityManager sstockersPUEntityManager;
    private java.util.List<shelfstockers.Stock> stockList;
    private java.util.List<shelfstockers.Stock> stockList1;
    private java.util.List<shelfstockers.Stock> stockList2;
    private java.util.List<shelfstockers.Stock> stockList3;
    private java.util.List<shelfstockers.Stock> stockList4;
    private java.util.List<shelfstockers.Stock> stockList5;
    private javax.persistence.Query stockQuery;
    private javax.persistence.Query stockQuery1;
    private javax.persistence.Query stockQuery2;
    private javax.persistence.Query stockQuery3;
    private javax.persistence.Query stockQuery4;
    private javax.persistence.Query stockQuery5;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
    
    




}
